### ISSUE TITLE
Would it be possible to port to GHC 9.6?

### ISSUE THREAD

**Issue by Mikolaj** [haskellari/strict-containers#12]
I wonder, perhaps relaxing the `strict` bound would suffice?

**Comment by infinity0** [comment]
I'm on holiday for a couple months and won't have much time to test this in depth, but could probably find some time to look at a PR and the resulting CI results. Or can deal with this myself once I'm back if you are happy to wait.

**Comment by Mikolaj** [comment]
It appears we are blocked on vector-binary-instances anyway. :(

**Comment by Mikolaj** [comment]
But thank you. :)

**Comment by Mikolaj** [comment]
I think it's possible we are now only blocked on our bound on `strict`. Could it be relaxed, perhaps just via a Hackage revisions?

**Comment by erikd** [comment]
I currently have the following in my `cabal.project` file:

```
allow-newer:
    strict-containers:strict
```

**Comment by infinity0** [comment]
If it's just a simple case of relaxing the version bound feel free to open a PR that will run CI. I'm completely context-swapped out of Haskell atm.

**Comment by erikd** [comment]
@infinity0 PR is https://github.com/haskellari/strict-containers/pull/13

I am also a Hackage trustee so I can do a metadata edit for this if you would like me to.

**Comment by infinity0** [comment]
Sure feel free & thanks! I'll leave this issue open to track adding 9.6 to CI in the future, once `ghcup` supports it.

**Comment by erikd** [comment]
> Sure feel free & thanks! I'll leave this issue open to track adding 9.6 to CI in the future, once `ghcup` supports it.

Done

**Comment by erikd** [comment]
@phadej Where to you propose moving it? The https://github.com/haskell group might be appropriate.

**Comment by phadej** [comment]
@erikd anywhere @infinity0 (as the only Hackage maintainer) seems fit. Out of `haskellari`.

**Comment by infinity0** [comment]
What concrete problem do you have with how I am maintaining this repo currently?

Might I remind you that I originally only agreed to move `strict` from the `haskell-strict` organisation to here if it was more collaboratively maintained, rather than just you deciding what should be in-or-out. If we move `strict-containers` away from here, I think `strict` should also be moved away from here, they form a related set of packages. We could them move into the old `haskell-strict` organisation if `haskell` isn't willing to accept them.

**Comment by phadej** [comment]
This is about `strict-containers`, not `strict`.

**Comment by erikd** [comment]
@infinity0 I am willing to take over maintainer ship of this package if you are too busy. 

The specific problems I have with this package is that dependencies are not updated in a timely manner (https://github.com/haskellari/strict-containers/issues/15). Currently using `allow-newer` but do not like to commit that to master.

**Comment by infinity0** [comment]
@erikd I just invited you to collaborate on this repo and also have added you to the hackage maintainers' group for this package. Feel free to bump the dependencies and release new versions.

Updating the actual upstream/contrib libraries are much more complex, because of the patching process. I described it previously in #14. Please do ask questions if any part of it isn't clear - or just leave it be for the time being. (Also, we can drop the vector part of it now, see #16.)

If the https://github.com/haskell group is happy to accept this package I'd be happy to move it there, but in the meantime would prefer to have it co-maintained within this group. Bear in mind it is not a "normal" haskell package and involves those hacky patches that require a different skill-set to maintain.

**Comment by erikd** [comment]
Version on `master` and on Hackage compiles with `ghc < 9.10`.
